services:
  - type: web
    name: glam_church_site
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py setup_site"
    startCommand: "gunicorn church_site.wsgi"
    envVars:
      - key: SECRET_KEY
        value: glam-church-secret-key-2026-xyz-abc
      - key: DEBUG
        value: "False"
