# Generated by Django 6.0.7 on 2026-07-11 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=False, help_text='Email subscribed members')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Fountain of Grace Church', max_length=200)),
                ('tagline', models.CharField(default='Where Faith Meets Destiny', max_length=300)),
                ('mission_statement', models.TextField(default='To raise a generation of passionate worshippers who impact their world with the love of Christ.')),
                ('vision_statement', models.TextField(default='A church where every soul finds purpose, every family finds strength, and every community finds transformation.')),
                ('address', models.TextField(default='12 Emmanuel Close, Lekki Phase 1, Lagos, Nigeria')),
                ('phone_primary', models.CharField(default='+234 802 000 0000', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(default='+234 802 000 0000', max_length=20)),
                ('email', models.EmailField(default='info@fountainofgrace.org', max_length=254)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com')),
                ('twitter_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.7286840761937!2d3.4699836750284266!3d6.430620793567657!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103bf53aec4dd92d%3A0x4a08d6b07ebf2d9f!2sLekki%20Phase%201%2C%20Lagos!5e0!3m2!1sen!2sng!4v1710000000000!5m2!1sen!2sng" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>')),
                ('hero_bible_verse', models.CharField(default='John 10:10', max_length=200)),
                ('hero_bible_text', models.TextField(default='I have come that they may have life, and have it to the full.')),
                ('founding_year', models.CharField(default='1999', max_length=10)),
                ('denomination', models.CharField(default='Pentecostal', max_length=100)),
                ('livestream_embed_url', models.URLField(blank=True, help_text='e.g. https://www.youtube.com/embed/VIDEOID', verbose_name='Livestream Embed URL')),
                ('livestream_channel_url', models.URLField(blank=True, default='https://youtube.com')),
                ('is_live_now', models.BooleanField(default=False, verbose_name='Live right now?')),
                ('bg_hero_file', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Hero BG — Upload')),
                ('bg_hero_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1604580864964-0462f5d5b1a8?w=1800&q=80', verbose_name='Hero BG — URL')),
                ('bg_about_file', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='About BG — Upload')),
                ('bg_about_url', models.URLField(blank=True, verbose_name='About BG — URL')),
                ('bg_sermons_file', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Sermons BG — Upload')),
                ('bg_sermons_url', models.URLField(blank=True, verbose_name='Sermons BG — URL')),
                ('bg_events_file', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Events BG — Upload')),
                ('bg_events_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1400&q=70', verbose_name='Events BG — URL')),
                ('bg_ministries_file', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Ministries BG — Upload')),
                ('bg_ministries_url', models.URLField(blank=True, verbose_name='Ministries BG — URL')),
                ('bg_testimonies_file', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Testimonies BG — Upload')),
                ('bg_testimonies_url', models.URLField(blank=True, verbose_name='Testimonies BG — URL')),
                ('bg_give_file', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Give CTA BG — Upload')),
                ('bg_give_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1400&q=70', verbose_name='Give CTA BG — URL')),
            ],
            options={
                'verbose_name': 'Church Settings',
                'verbose_name_plural': 'Church Settings',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='Church Auditorium', max_length=200)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Event Image — Upload')),
                ('image_url', models.URLField(blank=True, verbose_name='Event Image — URL')),
                ('is_featured', models.BooleanField(default=False)),
                ('registration_link', models.URLField(blank=True)),
                ('send_notification', models.BooleanField(default=True, help_text='Email subscribed members when created')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(blank=True, help_text='Upload JPG/PNG/WEBP poster', null=True, upload_to='flyers/', verbose_name='Flyer Image — Upload')),
                ('image_url', models.URLField(blank=True, help_text='Or paste an online image URL', verbose_name='Flyer Image — URL')),
                ('link_url', models.URLField(blank=True, help_text='Optional — clicking opens this URL')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Church Flyer / Poster',
                'verbose_name_plural': 'Church Flyers / Posters',
                'ordering': ['order', '-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('photo_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_senior_pastor', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-cross', help_text='Font Awesome class e.g. fas fa-fire', max_length=60)),
                ('bg_file', models.ImageField(blank=True, null=True, upload_to='ministries/', verbose_name='Card BG — Upload')),
                ('bg_url', models.URLField(blank=True, verbose_name='Card BG — URL')),
                ('leader_name', models.CharField(blank=True, max_length=100)),
                ('meeting_time', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notif_type', models.CharField(choices=[('event', 'Event'), ('announcement', 'Announcement'), ('sermon', 'Sermon'), ('general', 'General')], default='general', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('bank', 'Bank Transfer'), ('paystack', 'Paystack Online'), ('flutterwave', 'Flutterwave'), ('ussd', 'USSD'), ('other', 'Other')], default='bank', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ussd_code', models.CharField(blank=True, max_length=50)),
                ('api_public_key', models.CharField(blank=True, max_length=200, verbose_name='API Public Key')),
                ('icon_class', models.CharField(blank=True, default='fas fa-university', max_length=50)),
                ('giving_types', models.CharField(blank=True, default='Tithe,Offering,Special Seed,Missions,Building Fund', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('preacher', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('bible_passage', models.CharField(blank=True, max_length=100)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('service_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('other', 'Prefer not to say')], max_length=10)),
                ('membership_status', models.CharField(choices=[('new', 'New Member'), ('regular', 'Regular Member'), ('worker', 'Church Worker'), ('minister', 'Minister')], default='new', max_length=20)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('ministry_interest', models.CharField(blank=True, max_length=200)),
                ('notify_events', models.BooleanField(default=True, verbose_name='Notify: New Events')),
                ('notify_sermons', models.BooleanField(default=True, verbose_name='Notify: New Sermons')),
                ('notify_announcements', models.BooleanField(default=True, verbose_name='Notify: Announcements')),
                ('push_subscription', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('location', models.CharField(blank=True, default='Worldwide', max_length=150)),
                ('testimony', models.TextField()),
                ('category', models.CharField(choices=[('Healing', 'Healing'), ('Financial Breakthrough', 'Financial Breakthrough'), ('Marriage & Family', 'Marriage & Family'), ('Salvation', 'Salvation'), ('Career & Education', 'Career & Education'), ('Deliverance', 'Deliverance'), ('General', 'General')], default='General', max_length=50)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='testimonies/')),
                ('photo_url', models.URLField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Tick to show on website')),
                ('is_featured', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='core.memberprofile')),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-is_featured', '-date'],
            },
        ),
    ]
