# Generated by Django 6.0.7 on 2026-07-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_logo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Upload your church logo PNG/SVG (shown in navbar)', null=True, upload_to='logo/', verbose_name='Church Logo — Upload File'),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Or paste a URL to your logo image', verbose_name='Church Logo — URL'),
        ),
    ]
