# Generated by Django 6.1 on 2026-08-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logo_fields_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='title',
            field=models.CharField(blank=True, help_text="Short headline e.g. 'God healed my fibroid after 3 years!'", max_length=200, verbose_name='Testimony Title'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testimony',
            field=models.TextField(verbose_name='Full Testimony Text'),
        ),
    ]
