# Generated by Django 6.1 on 2026-08-09 15:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_testimony_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_about_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='backgrounds'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_events_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='backgrounds'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_give_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='backgrounds'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_hero_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='backgrounds'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_ministries_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='backgrounds'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_sermons_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='backgrounds'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_testimonies_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='backgrounds'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='logo_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='events'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='flyers'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='photo_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='leadership'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='photo_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='bg_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ministries'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='photo_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='testimonies'),
        ),
    ]
