# Generated by Django 6.1 on 2026-08-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cloudinary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_about_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='About BG — Upload'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_events_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Events BG — Upload'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_give_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Give CTA BG — Upload'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_hero_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Hero BG — Upload'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_ministries_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Ministries BG — Upload'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_sermons_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Sermons BG — Upload'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='bg_testimonies_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Testimonies BG — Upload'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Upload your church logo PNG/SVG (shown in navbar)', null=True, upload_to='logo/', verbose_name='Church Logo — Upload File'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Event Image — Upload'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload JPG/PNG/WEBP poster', null=True, upload_to='flyers/', verbose_name='Flyer Image — Upload'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='bg_file',
            field=models.ImageField(blank=True, null=True, upload_to='ministries/', verbose_name='Card BG — Upload'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='testimonies/'),
        ),
    ]
